#generate.target.violins.R
#creates violin plots of mature/target ratios for miRNAs and tasiRNAs as shown in Fig. 3C

#install.packages("extrafont")
library("extrafont")
#font_import()
loadfonts()

#install.packages("RColorBrewer")
library("RColorBrewer")

#install.packages('vioplot')
library("vioplot")

setwd('/Volumes/nodine/lab/members/michael/compFiles/sRNAs/projects/apps/smallRNA_spikeIns/scripts.for.ms/')  #user will have to change this to their working directory

master = read.table("methods.data.analysis/master_genes_Araport.txt", header=TRUE, sep='\t', row.names=1, strip.white=T)

Na = 6.02214179 * 10e23 * 1e-18

getFits <- function(sample, mix, scaling_factor){
  spike = read.table("methods.data.analysis/Analysis.txt", header=TRUE, sep="\t", row.names=2, strip.white=T)
  spike = subset(spike, select=paste("concentration.in.Mix.",mix,"..attomoles.ul.",sep=""))
  colnames(spike) = "molecules"
  
  #multiply by Avagadro's number, scaling factor and 1/1000 to determine number of molecules for each spike-in added
  #scaling_factor was the same (0.0002) all samples used in this study; scaling_factor = (ul of ERCC mix added) * (1/dilution of total ug that spike-in was added to) * (1/ERCC dilution) * (1/total ug)
  # = (1) * (1/50) * (1/200) * (1/0.5)
  spike = spike * Na * scaling_factor
  
  master_sub = subset(master, select = sample)
  
  #select ERCCs with values >= 1 TPM
  ERCC_all = merge(master_sub,spike, by = "row.names")
  row.names(ERCC_all) = ERCC_all$Row.names
  ERCC_exp = subset(ERCC_all, ERCC_all[,sample] >= 1, select = 2:3)
  colnames(ERCC_exp) = c("TPM","molecules")
  
  #log-based plot outperforms linear one so use this for modeling
  fit_log = lm(log(ERCC_exp$molecules,10) ~ log(ERCC_exp$TPM,10))
  
  #now get sRNA molecules  
  data_sRNA = read.table(paste("methods.data.analysis/small.RNA.Seq/",sample,"/smRNA_spikeIns/doseResponseTable_noTransform",sep=""), header=TRUE, sep="\t", row.names=1, strip.white=T)
  
  #now fit linear model and use to predict mpe
  fit_log_sRNA = lm(log(data_sRNA$mlcs,10) ~ log(data_sRNA$rpm..mean.,10))
    
  return(list(fit_log,fit_log_sRNA))
}

getVals_tar <- function(type){
  #Targets were selected from datasets generated by Addo-Quaye et al. (2008) Current Biology and predicted by the CleaveLand software (Addo-Quaye [2008] Bioinformatics) to be either Class 1 or Class 2 (confident) targets with p-values < 0.05
  data_axtell = read.table(paste("methods.data.analysis/","repMature_",type,"_fb_rpmThresh_1.0.results.Axtell_class_1and2.txt",sep=''), header=T, sep='\t', row.names=1, strip.white=T, quote="")

  #now extract TPM values for AGIs
  ##take subset of master corresponding to samples
  master_sub = subset(master, select = c('col0_fb1','col0_fb2','d234_fb1','d234_fb2'))  
  
  #get TPM values for targets
  targets_axtell = merge(master_sub,data_axtell, by='row.names')
  rownames(targets_axtell) = targets_axtell$Row.names
  targets_axtell = subset(targets_axtell, select = 2:11)
  colnames(targets_axtell) = c("col0_fb1_mRNA","col0_fb2_mRNA","d234_fb1_mRNA","d234_fb2_mRNA","sRNA","class","col0_fb1_sRNA","col0_fb2_sRNA","d234_fb1_sRNA","d234_fb2_sRNA")
  
  #calculate lm for sRNA and mRNA spike-ins from col0_fb
  col0_fb1_mRNA_fit = getFits("col0_fb1", 1, 0.0002)[[1]]
  col0_fb1_sRNA_fit = getFits("col0_fb1", 1, 0.0002)[[2]]

  col0_fb2_mRNA_fit = getFits("col0_fb2", 1, 0.0002)[[1]]
  col0_fb2_sRNA_fit = getFits("col0_fb2", 1, 0.0002)[[2]]
  
  d234_fb1_mRNA_fit = getFits("d234_fb1", 2, 0.0002)[[1]]
  d234_fb1_sRNA_fit = getFits("d234_fb1", 2, 0.0002)[[2]]
  
  d234_fb2_mRNA_fit = getFits("d234_fb2", 2, 0.0002)[[1]]
  d234_fb2_sRNA_fit = getFits("d234_fb2", 2, 0.0002)[[2]]
  
  #now apply model to precursor TPM and sRNA rpm values
  ##estimate individual molecules  
  col0_fb1_coeffs_mRNA = coefficients(col0_fb1_mRNA_fit)
  col0_fb1_coeffs_sRNA = coefficients(col0_fb1_sRNA_fit)

  col0_fb2_coeffs_mRNA = coefficients(col0_fb2_mRNA_fit)
  col0_fb2_coeffs_sRNA = coefficients(col0_fb2_sRNA_fit)
  
  d234_fb1_coeffs_mRNA = coefficients(d234_fb1_mRNA_fit)
  d234_fb1_coeffs_sRNA = coefficients(d234_fb1_sRNA_fit)
  
  d234_fb2_coeffs_mRNA = coefficients(d234_fb2_mRNA_fit)
  d234_fb2_coeffs_sRNA = coefficients(d234_fb2_sRNA_fit)
  
  absolute = cbind(targets_axtell$sRNA, 10^(col0_fb1_coeffs_mRNA[1] + col0_fb1_coeffs_mRNA[2]*log(targets_axtell$col0_fb1_mRNA,10)), 
                   10^(col0_fb2_coeffs_mRNA[1] + col0_fb2_coeffs_mRNA[2]*log(targets_axtell$col0_fb2_mRNA,10)),
                   10^(d234_fb1_coeffs_mRNA[1] + d234_fb1_coeffs_mRNA[2]*log(targets_axtell$d234_fb1_mRNA,10)),
                   10^(d234_fb2_coeffs_mRNA[1] + d234_fb2_coeffs_mRNA[2]*log(targets_axtell$d234_fb2_mRNA,10)),
                   10^(col0_fb1_coeffs_sRNA[1] + d234_fb1_coeffs_sRNA[2]*log(targets_axtell$col0_fb1_sRNA,10)),
                   10^(col0_fb2_coeffs_sRNA[1] + d234_fb2_coeffs_sRNA[2]*log(targets_axtell$col0_fb2_sRNA,10)),
                   10^(d234_fb1_coeffs_sRNA[1] + d234_fb1_coeffs_sRNA[2]*log(targets_axtell$d234_fb1_sRNA,10)),
                   10^(d234_fb2_coeffs_sRNA[1] + d234_fb2_coeffs_sRNA[2]*log(targets_axtell$d234_fb2_sRNA,10)))
  dimnames(absolute)=list(c(row.names(targets_axtell)),c("sRNA","col0_fb1_mRNA_mlcs","col0_fb2_mRNA_mlcs","d234_fb1_mRNA_mlcs","d234_fb2_mRNA_mlcs","col0_fb1_sRNA_mlcs","col0_fb2_sRNA_mlcs","d234_fb1_sRNA_mlcs","d234_fb2_sRNA_mlcs"))
    
  return(absolute)
}

#get miRNA molecules with rpm values of at least one
absolute_tas = getVals_tar('tasiRNAs')
absolute_mir = getVals_tar('miRNAs')

#add pseudo count of 1 mlc to each in order to calculate ratios (a couple had values = 0)
pseudo = 1
absolute_tas = absolute_tas + pseudo
absolute_mir = absolute_mir + pseudo

col0_fb_tas_ratio = ((log(absolute_tas[,'col0_fb1_sRNA_mlcs']/absolute_tas[,'col0_fb1_mRNA_mlcs'],2)) + (log(absolute_tas[,'col0_fb2_sRNA_mlcs']/absolute_tas[,'col0_fb2_mRNA_mlcs'],2)))/2
d234_fb_tas_ratio = ((log(absolute_tas[,'d234_fb1_sRNA_mlcs']/absolute_tas[,'d234_fb1_mRNA_mlcs'],2)) + (log(absolute_tas[,'d234_fb2_sRNA_mlcs']/absolute_tas[,'d234_fb2_mRNA_mlcs'],2)))/2
col0_fb_mir_ratio = ((log(absolute_mir[,'col0_fb1_sRNA_mlcs']/absolute_mir[,'col0_fb1_mRNA_mlcs'],2)) + (log(absolute_mir[,'col0_fb2_sRNA_mlcs']/absolute_mir[,'col0_fb2_mRNA_mlcs'],2)))/2
d234_fb_mir_ratio = ((log(absolute_mir[,'d234_fb1_sRNA_mlcs']/absolute_mir[,'d234_fb1_mRNA_mlcs'],2)) + (log(absolute_mir[,'d234_fb2_sRNA_mlcs']/absolute_mir[,'d234_fb2_mRNA_mlcs'],2)))/2

col_v <- brewer.pal(4,"Paired") 
col_v = c(col_v[3],col_v[1])
name_v = c("flowers","d234","","flowers","d234")

pdf("figure.3/sRNA.target.violin.pdf", family='Arial', useDingbats=F)
par(las=1)
vioplot(col0_fb_mir_ratio,d234_fb_mir_ratio,c(0),col0_fb_tas_ratio,d234_fb_tas_ratio, col='white', names=name_v)
vioplot(col0_fb_mir_ratio,col=col_v[1], at=1, add=T)
vioplot(d234_fb_mir_ratio,col=col_v[2], at=2, add=T)
vioplot(col0_fb_tas_ratio,col=col_v[1], at=4, add=T)
vioplot(d234_fb_tas_ratio,col=col_v[2], at=5, add=T)
abline(h=0, lwd=2, lty=2)
dev.off()

ks.test(col0_fb_mir_ratio,d234_fb_mir_ratio)$p.value
ks.test(col0_fb_tas_ratio,d234_fb_tas_ratio)$p.value

